version: 2
project_name: agfapi

before:
  hooks:
    - go mod tidy

builds:
  - binary: agfapi
    main: ./cmd/agfapi
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.version=v{{ .Version }}"

archives:
  - formats:
      - binary
    name_template: >-
      {{ .ProjectName }}_{{- tolower .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
